Add Deployment Key generation

diff --git a/ouigo b/ouigo
--- a/ouigo
+++ b/ouigo
@@ -25,11 +25,14 @@ Available options:
                     (default: ouigo.conf)
   -u, --username    override the Grid5000 username from the config file
   -l, --location    override the Grid5000 access location from the config file
+  -s, --pivatekey   override the SSH private key to use in the deployment
+  -p, --publickey   override the SSH public key to use in the deployment
   -h, --help        show this message
 
 Available actions:
   setup    runs the initial setup of all jobs on sites
   info     displays information about the current reservations
+  backup   trigger a manual backup of the running machines
   clear    remove active crontab and cancel jobs
 
 Configuration file:
@@ -45,8 +48,8 @@ Copyright (c) 2020 - Johannes Wünsche, Fin Christensen"
 }
 
 parse_cli_args() {
-    OPTIONS="hc:u:l:"
-    LONGOPTS="help,configfile:,username:,location:"
+    OPTIONS="hc:u:l:p:s:"
+    LONGOPTS="help,configfile:,username:,location:,publickey:,privatekey:"
 
     # shellcheck disable=SC2152
     ! PARSED=$(getopt --options="${OPTIONS}" --longoptions="${LONGOPTS}" --name "$0" -- "$@")
@@ -78,6 +81,14 @@ parse_cli_args() {
                 ;;
             -l|--location)
                 OUIGO_G5K_ACCESS_LOCATION="$2"
+                shift 2
+                ;;
+            -p|--publickey)
+                OUIGO_SSH_PUBLIC_KEY="$2"
+                shift 2
+                ;;
+            -s|--privatekey)
+                OUIGO_SSH_PRIVATE_KEY="$2"
                 shift 2
                 ;;
             --)
@@ -128,6 +139,8 @@ parse_config_file() {
 load_default_config() {
     set_if_undefined OUIGO_G5K_ACCESS_LOCATION lille
     set_if_undefined OUIGO_G5K_USERNAME ""
+    set_if_undefined OUIGO_SSH_PRIVATE_KEY "./scionlab_grid5000_rsa"
+    set_if_undefined OUIGO_SSH_PUBLIC_KEY "./scionlab_grid5000_rsa.pub"
 }
 
 __log__ () {
@@ -240,7 +253,10 @@ get_node_name() {
 
 setup_machine() {
     # 1 - machine address/name
+    scp "$HOME/scionlab.prv" "$HOME/scionlab.pub" "root@${1}:"
     ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" root@"$1" "
+    mv scionlab.prv .ssh/id_rsa
+    cat scionlab.pub >> .ssh/authorized_keys
     useradd scionlab
     usermod -aG sudo scionlab
     echo 'scionlab ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
@@ -260,13 +276,40 @@ ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDmAztsnrE8u3IiKiPZ/ys+8eDr33BNO1FWlYDfVaaz
 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILwpdjGYdUL498BpaIfARfrqoe8WBaaEO+b5vBef4xxV matzf@thumper
 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQDaGpk/mUd0aDPYvLWbKvg8aDNkWbDw+xbuAjkHheXUmkNRAQqV2IlsNHGAtZRPH+SJlW+mRSUavVexcFPqyKb8VF9RYcdSWn+tjUvIoY81rIfO0gKYzr4G2ACWEV+vey1VlP7if8k3boNZbCG1EklwEnpl7P5fZoAsDhWJguh/9xIDEhq1bh6H7GfQJagcnS+rUvtXbqwqiPVDYKO3BJaALVukOcLdpxcEDQ5q4Qv5fNUBeQBliIKS7FrWsZNdVhJPi8TYWFmgyRGXzVj2EYX/vIcX0ezj7f5QIQacJUnSRg6eozYyO/4ESgRKjyn+toTENjrMChy7XjUIsqMWwshUX68OnzSBOhEgbkqCroYDVtHg4/OmgsVd9sJWWCT40Z0lfWVPISG/pCNrS4srUTyTyfA2SDyv+3WAWL4VG+lh/duFte2qKxRVOPKs/eg7gRUQJAGlYZBhl2FOWZGn5r60wX3Hh4zp0qEOyq2ULO8uCd4E46RqXL61kVHUL/v/yVmcB8XPmpAJaFJyASIzYNsre1oI6Axvhk8eUwWeZHKCl5tZckHh1D+Y+3fx9bkgsa12c44U1ErkRrLInK1uLdHuRMAN6DQpNJPcDzp/dWDzpBiZmIaW47mcQjgcjj+OEVoASX2s7QV6dis8wfg6yGl35bz3Xgd9YWigOPWFcRbTqeZCi2N0Wg6Fn9eoV9qBSrs+81t7LGRCGw7UtU4YDbMlIu6SnAEKFbGg2ylOvO5LEAdaMuWq14uC8HWigp2kLlkOlzE0ZBES5N65gLouAs44CcV7hj52sN4MdY4T7nh35Zrjks1h8nCcs5kvB2fE0imjD5R1YNHa37xQrHYajQ4xlYCXDiZkFX7O2gRT9gaLJ4NV8jcOIKRap7XgppcSswEV9X4MzmpyYkOcAVGqm/Bfeig46UOnY+TKn1VQVqSx9iWzCpyEWdHELh2ku1mH7yEWFlNQCfg0Y65KN6DTmQUvPzUSsS7lHDzvNdnyJ/g9dSgI9Vo7cOdM+pYPsMjFuDasUGdt9nlxjFOiv4clcIzuhGqhtOMhTNrSAdAqIQIc9Tv1p+R5b5nUDfYs5hCCylT/WBVfMPPowjYYsIzAGYOW6ka+kYLCWFPWjdPaQdq1LQXU+YIVbVZBoIyv50PD/IoWBNbeOBbHwqN4OHcp9Pobv449qrGz1VYvEFWLSGQNxS7RpNZQsbJ0w5FZaL9nEbNIWLJfr+6D78nHu7DycY0JCwmcKK7bmEVzgUIUfBPcHgl9+OsZE2MLxPTe61Pj/zhYE4UPnKQMd5xcHv0pd7p4TT40Vm4jkabdhBcTGpwmZTbxRfAGyNfpUyg0gjAQDlY3rMeZIXA0/Sh6X2cR4z51
 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQCxIhVVb4r+7/OGpEkWCfSh8jSqjPQsb4h2Jorxw+tikaxPEk4tawjcVzn29aKqHZswMQ/Zhc0F7uHVAiv4JXWbVIqG3fhe1r1ZHWGmAbftF4aMDxUVMj0J4xyO/TPHJbEChqAhx6LZHxRjQi2wGMGWbYcaINEN6IExc5C+SBqs8DJSBeF0TTkGhRFkgAlp7kPSVlyGkys/uhGPzniTpjk3ROjHqlCnDPCqWqxXqFbWAgZYAt7MvxiED/IoVRZqeFuEWPni0rhB40JuIkqLumbrUDVnbIP7yBVCHpJWvW03we4dUGxzkcQAdAVXJY1Icn9k7+IK3d/fSIh4T70J3VsHXwuAMLG5tHiIqUnoxAjxy30Wj5HzvaQnP9TkP627HdUbD6EXyJrwwxzi6MdQR14IRQfauzCBraCArm22BKeaNh3bjAv4URCm7I2GlJnF0oofufjJ9AbGq/6xjnDhCJIdgaYWNjbPj2GZRQNK18xzxCPvpHZDg9k37Jpgp+gUG0bbA7AayFapMFE1v0OoqvwHPamDUavKkP49Kfog1yeW5NzWy9wrZyP+ZVYRuKqqK548SWIw1rYCv8OETJWTtmD6zgmFeCNXIqE+PYxd9lXpQHKSfBCvwUYhLjXL3zm8J3UGGXsZorUDjChTfXILSeMOoldahej7dGNrU9aqstixMKVO3zIYjCllF7yO/0FqmoHqpCX1dp9ExIqsdlQUoqBszR2diOyfJV1lijTUbGPI8qcQKCSjaE4FpCFrRekNvkZlmqvQGY1wFe+kpXKvkbxFWK2AdxAv0i3f/HaytjSbx9riaG6usp2G/xgVkJTHFkzf4qGzVN030O0kvvz5Zy8C8depsib7x8KqTFGEMTPtPALs0JhFV6jK/U7sT6KK8xqwhijrcX/F4xTXExIoGjwR2RYCwiNO8qxT6aoFAHk1mYBRizTIrTJRfni2YKvIU00MaVyVdOGUuRws1CZNQzJaaM4IMOxQY+JPKy1BqSz5fiZSc1eedo6hXrW7G2cFIEbVT39ospum9nlUEWF+g12yxhXiMK3NmxU47d3jpI55919o9fQeV52houqJBQfWxeZOnD89VluMK9T7oUjvoNLDTKpCQuovTlnw0ZEWGsjVDEffarf8DCL1RhhTXsy8k83pxHVPsKT5J7K4sb4BWPef18OtLq+qvssEAJa5wTALlYKTrpY8EswkTSwGp4sNMQ35ZcS7shQwKeL+XqkqsS1+s3+zt7fAcfacwzDI6sCCiJiKkIwkyLbpDXJYy1sdkQEt3JTPbdNrRcshFfgaR1kkYvFJydvPQK0l3/kNa2KGdfpmmEL1uBEV/1wnwQRpYGZpyfert08SdP9VTVuPwx+B jwuensch@byzantium' > /home/scionlab/.ssh/authorized_keys
+    echo '#!/bin/bash
+# Create image and copy to frontend machine
+echo \"Creating image...\"
+rm -rf /tmp/image.tgz
+tgz-g5k -f /tmp/image.tgz
+
+# default endlocation
+endlocation=frontend
+
+# Check for connectivity, atm we cannot connect directly to one machine in lille
+if ! ping -c 1 frontend >/dev/null 2>&1
+then
+    args=\"-o ProxyJump=root@10.1.8.9,jwuensche@frontend\"
+    endlocation=lille
+fi
+
+echo \"Copying image to frontend...\"
+# Make ssh options available, for e.g. identity file
+scp \""'${*}'"\" \""'${args}'\"" /tmp/image.tgz \"jwuensche@"'${endlocation}'":scionlab.tgz\" > /dev/null 2>&1 || exit 1
+# Replace old image with new one
+# We need a key for that, gonna use my account for the time being
+echo \"Refreshing kaenv3 entry...\"
+ssh  \""'${*}'"\" \""'${args}'"\" \"jwuensche@"'${endlocation}'"\" \"kaenv3 -d scionlab > /dev/null 2>&1 || kaenv3 -a scionlab.env\" > /dev/null 2>&1 || exit 1
+echo \"Done.\"
+' > /usr/bin/backup_image
+    chmod +x /usr/bin/backup_image
     chown -R scionlab /home/scionlab
     chsh -s /bin/bash scionlab
-" > /dev/null 2> /dev/null
+" > /dev/null 2>&1
 }
 
 wait_for_environment() {
     # 1 - machine address/name
+    local location
     loginfo "Waiting for environment to be deployed"
     loginfo "This requires rebooting and bootstrapping the machines, this may take a while..."
     while true
@@ -274,8 +317,15 @@ wait_for_environment() {
         sleep 10
         if ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o BatchMode=yes root@"$1" 'if [[ $(uname -a) =~ "Ubuntu" ]]; then exit 0; else exit 1; fi' > /dev/null 2>/dev/null
         then
-            loginfo "Connecting possible, setting up..."
-            setup_machine "$1"
+            location=$(echo "$1" | cut -d '_' -f 2)
+            if ! stat scionlab.tgz > /dev/null 2>&1
+            then
+                loginfo "Connecting possible, setting up..."
+                setup_machine "$1"
+            else
+                loginfo "Connection possbile, skipping setup because already existing image has been used"
+            fi
+
             break
         fi
     done
@@ -294,9 +344,18 @@ reserve_job() {
 
     # Get nodes and check availability there is a dummy `sleep infinity` command to keep the job alive
     # the $OAR_NODEFILE has to be evaluated on the machine itself, so disregard the shellcheck warning here
-    node_result=$(curl -s https://api.grid5000.fr/3.0/sites/"$1"/jobs \
-                    -X POST -H 'Content-Type: application/json' \
-                    -d "{\"resources\":\"{eth_count>=$5}/nodes=1,walltime=1\",\"command\":\"kadeploy3 -k -e ubuntu1804-x64-min -f \$OAR_NODEFILE; sleep infinity\", \"name\":\"machine_$3_$4\", \"types\":[\"deploy\"]}")
+    if ! ssh "${USER}@${1}" stat scionlab.tgz >/dev/null 2>&1
+    then
+        # No image created before
+        node_result=$(curl -s https://api.grid5000.fr/3.0/sites/"$1"/jobs \
+                        -X POST -H 'Content-Type: application/json' \
+                        -d "{\"resources\":\"{eth_count>=$5}/nodes=1,walltime=1\",\"command\":\"kadeploy3 -k -e ubuntu1804-x64-min -f \$OAR_NODEFILE; sleep infinity\", \"name\":\"machine_$3_$4\", \"types\":[\"deploy\"]}")
+    else
+        # Image already exists, using that one
+        node_result=$(curl -s https://api.grid5000.fr/3.0/sites/"$1"/jobs \
+                        -X POST -H 'Content-Type: application/json' \
+                        -d "{\"resources\":\"{eth_count>=$5}/nodes=1,walltime=1\",\"command\":\"kadeploy3 -k -e scionlab -f \$OAR_NODEFILE; sleep infinity\", \"name\":\"machine_$3_$4\", \"types\":[\"deploy\"]}")
+    fi
 
     nodeid=$(echo "${node_result}" | jq '.uid')
     touch "${CACHE_DIR}/node_$1_${nodeid}_$5"
@@ -384,7 +443,8 @@ reserve_vlan() {
 
     start=$(curl -s -X GET "https://api.grid5000.fr/stable/sites/$1/internal/oarapi/jobs/${vlan_job_id}.json" | jq '.scheduled_start')
     loginfo "Reserved VLAN in $1 (Job ID ${vlan_job_id})"
-    time_to=$(echo "${start}" - "$(date +'%s')" | bc)
+    time_to=$(echo "$(date +'%s')" - "${start}" | bc)
+    echo "${time_to}"
     # Check if reservations is scheduled to start in the next 5 minutes or if the check should be skipped
     if [[ "${time_to}" -gt 300 ]] && [[ -z "$3" ]]
     then
@@ -455,6 +515,29 @@ location_has_nodes() {
     test "${#nfile[@]}" -gt 0
 }
 
+distribute_ssh_key() {
+    # ditributing the generated ssh key to the machines in grid5000
+    # we choose all the sites as we in general don't care
+    local sites
+    local jump=""
+    sites=(nancy lille lyon luxembourg nantes rennes grenoble sophia)
+    if ! is_running_on_g5k
+    then
+        jump="-o ProxyJump=${OUIGO_G5K_USERNAME}@access.grid5000.fr"
+    fi
+
+    for site in "${sites[@]}"
+    do
+        if ssh "${jump}" "${OUIGO_G5K_USERNAME}@${site}" "test -r scionlab.pub" && [[ $(sha1sum "${OUIGO_SSH_PUBLIC_KEY}") != $(ssh "${jump}" "${OUIGO_G5K_USERNAME}@${site}" "sha1sum scionlab.pub") ]]
+        then
+            logerror "Keys in Grid5000 ${site} do not match with your current key, please check if you cleared first or using the correct keys for this deployment"
+        fi
+        scp "${jump}" "${OUIGO_SSH_PRIVATE_KEY}" "${OUIGO_G5K_USERNAME}@${site}:scionlab.prv" > /dev/null
+        scp "${jump}" "${OUIGO_SSH_PUBLIC_KEY}" "${OUIGO_G5K_USERNAME}@${site}:scionlab.pub" > /dev/null
+        ssh -J "${OUIGO_G5K_USERNAME}@access.grid5000.fr" "${OUIGO_G5K_USERNAME}@${site}" "cat scionlab.pub >> .ssh/authorized_keys" > /dev/null
+    done
+}
+
 setup() {
     local node_nancy
     local node_lille
@@ -465,8 +548,14 @@ setup() {
     reserve_job nancy gros 1293 1391 4
     reserve_job lille chiclet 1294 1390 2
 
+
     node_nancy=$(get_node nancy)
     node_lille=$(get_node lille)
+
+    # Add deployment key to the mix
+    ssh "root@${node_lille}" "mv scionlab.prv .ssh/id_rsa && cat scionlab.pub >> .ssh/authorized_keys"
+    scp scionlab.prv scionlab.pub "root@${node_nancy}:"
+    ssh "root@${node_nancy}" "mv scionlab.prv .ssh/id_rsa && cat scionlab.pub >> .ssh/authorized_keys"
 
     network_machine "${node_lille}" "eth1" 1390
     # Set up the eno2 interface of lille before disconnecting it from g5k
@@ -480,6 +569,33 @@ ip route add 10.1.8.0/24 dev eno2"
     network_machine "${node_nancy}" "eth2" 1391
     network_machine "${node_nancy}" "eth3" 1390
     get_cron
+
+    local scionlab_env
+    scionlab_env="\"---
+name: scionlab
+version: 2020091021
+description: base image scionlab
+author: johannes.wuensche@ovgu.de
+visibility: private
+destructive: false
+os: linux
+image:
+  file: /home/jwuensche/scionlab.tgz
+  kind: tar
+  compression: gzip
+postinstalls:
+- archive: server:///grid5000/postinstalls/g5k-postinstall.tgz
+  compression: gzip
+  script: g5k-postinstall --net netplan
+boot:
+  kernel: \\\"/vmlinuz\\\"
+  initrd: \\\"/initrd.img\\\"
+filesystem: ext4
+partition_type: 131
+multipart: false\""
+    # We want client side escaping here
+    ssh "${OUIGO_G5K_USERNAME}@lille" "echo ${scionlab_env} > scionlab.env"
+    ssh "${OUIGO_G5K_USERNAME}@nancy" "echo ${scionlab_env} > scionlab.env"
 }
 
 get_cron() {
@@ -726,6 +842,15 @@ clear() {
     loginfo "Deleting crontab"
     crontab -r > /dev/null 2>&1 || true # don't care if this fails
 
+    loginfo "Removing deployment key from locations and local session"
+    local locations
+    locations=(nancy lille lyon sophia rennes grenoble luxembourg nantes)
+    for site in "${locations[@]}"
+    do
+        ssh "${OUIGO_G5K_USERNAME}@${site}.grid5000.fr" "stat scionlab.pub >/dev/null 2>&1 && cat .ssh/authorized_keys | grep -v \"\$(cat scionlab.pub)\" > .ssh/authorized_keys && rm scionlab.pub scionlab.prv" > /dev/null 2>&1
+    done
+    rm "${OUIGO_SSH_PRIVATE_KEY}" "${OUIGO_SSH_PUBLIC_KEY}" > /dev/null 2>&1 || true
+
     loginfo "Removing cache"
     rm -rf "${CACHE_DIR}"
 }
@@ -769,18 +894,80 @@ ensure_running_on_g5k() {
             scp "${OUIGO_CONFIG_FILE}" "${OUIGO_G5K_USERNAME}@access.grid5000.fr:${OUIGO_G5K_ACCESS_LOCATION}"
         fi
 
+        if [[ "${OUIGO_ACTION}" == "clear" ]] && stat "${OUIGO_SSH_PRIVATE_KEY}" > /dev/null 2>&1
+        then
+            loginfo "Removing local deployment key"
+            rm "${OUIGO_SSH_PRIVATE_KEY}" "${OUIGO_SSH_PUBLIC_KEY}" > /dev/null 2>&1 || true
+        fi
+
         ssh -J "${OUIGO_G5K_USERNAME}@access.grid5000.fr" \
             "${OUIGO_G5K_USERNAME}@${OUIGO_G5K_ACCESS_LOCATION}.grid5000.fr" \
             bash ./ouigo "$@"
         exit "$?"
     fi
+}
 
+check_keys() {
+    if [[ "${OUIGO_ACTION}" == "setup" ]] || [[ "${OUIGO_ACTION}" == "backup" ]]
+    then
+        if ! stat "${OUIGO_SSH_PRIVATE_KEY}" > /dev/null 2>&1 && ! stat "${OUIGO_SSH_PUBLIC_KEY}" > /dev/null 2>&1
+        then
+            logwarn "No local deployment key has been found, one will be generated now"
+            ssh-keygen -q -C "scionlab@gri5000deployment" -t rsa -b 8192 -f "${OUIGO_SSH_PRIVATE_KEY}" -N ""
+            distribute_ssh_key
+        fi
+
+        if [[ "${OUIGO_ACTION}" == "setup" ]] && ! stat "${OUIGO_SSH_PRIVATE_KEY}" > /dev/null 2>&1
+        then
+            logwarn "New setup requested, triggering build of new deployment key"
+            ssh-keygen -q -C "scionlab@gri5000deployment" -t rsa -b 8192 -f "${OUIGO_SSH_PRIVATE_KEY}" -N ""
+            distribute_ssh_key
+        fi
+
+        if ! stat "${OUIGO_SSH_PRIVATE_KEY}" > /dev/null 2>&1
+        then
+            logerror "Only public key found, are you missing the private one?"
+            return
+        fi
+
+        if ! stat "${OUIGO_SSH_PUBLIC_KEY}" > /dev/null 2>&1
+        then
+            logerror "Only private key found, are you missing the public one?"
+            return
+        fi
+
+        if [[ ! -r "${OUIGO_SSH_PRIVATE_KEY}" ]]
+        then
+            logerror "No readable private ssh key under path ${OUIGO_SSH_PRIVATE_KEY}"
+            return
+        fi
+
+        if [[ ! -r "${OUIGO_SSH_PUBLIC_KEY}" ]]
+        then
+            logerror "No readable public ssh key under path ${OUIGO_SSH_PRIVATE_KEY}"
+            return
+        fi
+    fi
+}
+
+backup() {
+    # Manual action for writing the images to the frontend
+    # useful for creating the initial images used in g5k
+    local node_nancy
+    cd "${CACHE_DIR}" > /dev/null 2>@1 || logerror "Deployment not started yet, aborting..."
+    node_nancy=$(get_node nancy)
+    ssh root@"${node_nancy}" "backup_image" > /dev/null 2>&1
+    # Connect to the second machine this is stationary for this setup
+    # If you choose another machine with more interface this jump host
+    # is not required.
+    ssh -J root@"${node_nancy}" root@10.1.8.7 "bash backup.sh"
 }
 
 parse_cli_args "$@"
 parse_config_file
 load_default_config
 
+check_keys
 ensure_running_on_g5k "$@"
 
 case "${OUIGO_ACTION}" in
@@ -796,6 +983,9 @@ case "${OUIGO_ACTION}" in
         ;;
     clear)
         clear
+        ;;
+    backup)
+        backup
         ;;
     *)
         echo "$0: Invalid action \`${OUIGO_ACTION}\`. Use \`--help\` to see a list of available actions!"
